@echo off
cd /d %~dp0
echo 开始测试服务动态上下线...

REM 启动Zookeeper（如果尚未启动）
echo 确保Zookeeper服务已启动...

REM 第一阶段：启动初始服务节点
echo.
echo 第一阶段：启动初始服务节点...
start "Server1" cmd /c "java -cp target/classes;D:\maven-repo\repository\org\projectlombok\lombok\1.18.30\lombok-1.18.30.jar;D:\maven-repo\repository\io\netty\netty-all\4.1.65.Final\netty-all-4.1.65.Final.jar;D:\maven-repo\repository\org\apache\curator\curator-recipes\5.1.0\curator-recipes-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-framework\5.1.0\curator-framework-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-client\5.1.0\curator-client-5.1.0.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper\3.6.0\zookeeper-3.6.0.jar;D:\maven-repo\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper-jute\3.6.0\zookeeper-jute-3.6.0.jar;D:\maven-repo\repository\org\apache\yetus\audience-annotations\0.5.0\audience-annotations-0.5.0.jar;D:\maven-repo\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-epoll\4.1.45.Final\netty-transport-native-epoll-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-unix-common\4.1.45.Final\netty-transport-native-unix-common-4.1.45.Final.jar;D:\maven-repo\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\maven-repo\repository\org\slf4j\slf4j-api\2.0.9\slf4j-api-2.0.9.jar;D:\maven-repo\repository\ch\qos\logback\logback-classic\1.4.11\logback-classic-1.4.11.jar;D:\maven-repo\repository\ch\qos\logback\logback-core\1.4.11\logback-core-1.4.11.jar;D:\maven-repo\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;D:\maven-repo\repository\com\google\protobuf\protobuf-java\4.30.2\protobuf-java-4.30.2.jar;D:\maven-repo\repository\com\github\rholder\guava-retrying\2.0.0\guava-retrying-2.0.0.jar;D:\maven-repo\repository\com\google\guava\guava\33.4.8-jre\guava-33.4.8-jre.jar;D:\maven-repo\repository\com\google\guava\failureaccess\1.0.3\failureaccess-1.0.3.jar;D:\maven-repo\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\maven-repo\repository\org\jspecify\jspecify\1.0.0\jspecify-1.0.0.jar;D:\maven-repo\repository\com\google\errorprone\error_prone_annotations\2.36.0\error_prone_annotations-2.36.0.jar;D:\maven-repo\repository\com\google\j2objc\j2objc-annotations\3.0.0\j2objc-annotations-3.0.0.jar;D:\maven-repo\repository\com\google\code\findbugs\jsr305\2.0.2\jsr305-2.0.2.jar server.TestServer"
ping -n 5 127.0.0.1 > nul

REM 启动客户端进行测试
echo.
echo 启动客户端进行初始测试...
java -cp target/classes;D:\maven-repo\repository\org\projectlombok\lombok\1.18.30\lombok-1.18.30.jar;D:\maven-repo\repository\io\netty\netty-all\4.1.65.Final\netty-all-4.1.65.Final.jar;D:\maven-repo\repository\org\apache\curator\curator-recipes\5.1.0\curator-recipes-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-framework\5.1.0\curator-framework-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-client\5.1.0\curator-client-5.1.0.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper\3.6.0\zookeeper-3.6.0.jar;D:\maven-repo\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper-jute\3.6.0\zookeeper-jute-3.6.0.jar;D:\maven-repo\repository\org\apache\yetus\audience-annotations\0.5.0\audience-annotations-0.5.0.jar;D:\maven-repo\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-epoll\4.1.45.Final\netty-transport-native-epoll-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-unix-common\4.1.45.Final\netty-transport-native-unix-common-4.1.45.Final.jar;D:\maven-repo\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\maven-repo\repository\org\slf4j\slf4j-api\2.0.9\slf4j-api-2.0.9.jar;D:\maven-repo\repository\ch\qos\logback\logback-classic\1.4.11\logback-classic-1.4.11.jar;D:\maven-repo\repository\ch\qos\logback\logback-core\1.4.11\logback-core-1.4.11.jar;D:\maven-repo\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;D:\maven-repo\repository\com\google\protobuf\protobuf-java\4.30.2\protobuf-java-4.30.2.jar;D:\maven-repo\repository\com\github\rholder\guava-retrying\2.0.0\guava-retrying-2.0.0.jar;D:\maven-repo\repository\com\google\guava\guava\33.4.8-jre\guava-33.4.8-jre.jar;D:\maven-repo\repository\com\google\guava\failureaccess\1.0.3\failureaccess-1.0.3.jar;D:\maven-repo\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\maven-repo\repository\org\jspecify\jspecify\1.0.0\jspecify-1.0.0.jar;D:\maven-repo\repository\com\google\errorprone\error_prone_annotations\2.36.0\error_prone_annotations-2.36.0.jar;D:\maven-repo\repository\com\google\j2objc\j2objc-annotations\3.0.0\j2objc-annotations-3.0.0.jar;D:\maven-repo\repository\com\google\code\findbugs\jsr305\2.0.2\jsr305-2.0.2.jar client.TestClient
ping -n 3 127.0.0.1 > nul

REM 第二阶段：启动第二个服务节点
echo.
echo 第二阶段：启动第二个服务节点...
start "Server2" cmd /c "java -cp target/classes;D:\maven-repo\repository\org\projectlombok\lombok\1.18.30\lombok-1.18.30.jar;D:\maven-repo\repository\io\netty\netty-all\4.1.65.Final\netty-all-4.1.65.Final.jar;D:\maven-repo\repository\org\apache\curator\curator-recipes\5.1.0\curator-recipes-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-framework\5.1.0\curator-framework-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-client\5.1.0\curator-client-5.1.0.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper\3.6.0\zookeeper-3.6.0.jar;D:\maven-repo\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper-jute\3.6.0\zookeeper-jute-3.6.0.jar;D:\maven-repo\repository\org\apache\yetus\audience-annotations\0.5.0\audience-annotations-0.5.0.jar;D:\maven-repo\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-epoll\4.1.45.Final\netty-transport-native-epoll-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-unix-common\4.1.45.Final\netty-transport-native-unix-common-4.1.45.Final.jar;D:\maven-repo\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\maven-repo\repository\org\slf4j\slf4j-api\2.0.9\slf4j-api-2.0.9.jar;D:\maven-repo\repository\ch\qos\logback\logback-classic\1.4.11\logback-classic-1.4.11.jar;D:\maven-repo\repository\ch\qos\logback\logback-core\1.4.11\logback-core-1.4.11.jar;D:\maven-repo\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;D:\maven-repo\repository\com\google\protobuf\protobuf-java\4.30.2\protobuf-java-4.30.2.jar;D:\maven-repo\repository\com\github\rholder\guava-retrying\2.0.0\guava-retrying-2.0.0.jar;D:\maven-repo\repository\com\google\guava\guava\33.4.8-jre\guava-33.4.8-jre.jar;D:\maven-repo\repository\com\google\guava\failureaccess\1.0.3\failureaccess-1.0.3.jar;D:\maven-repo\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\maven-repo\repository\org\jspecify\jspecify\1.0.0\jspecify-1.0.0.jar;D:\maven-repo\repository\com\google\errorprone\error_prone_annotations\2.36.0\error_prone_annotations-2.36.0.jar;D:\maven-repo\repository\com\google\j2objc\j2objc-annotations\3.0.0\j2objc-annotations-3.0.0.jar;D:\maven-repo\repository\com\google\code\findbugs\jsr305\2.0.2\jsr305-2.0.2.jar server.TestServer"
ping -n 5 127.0.0.1 > nul

REM 再次测试客户端
echo.
echo 再次测试客户端...
java -cp target/classes;D:\maven-repo\repository\org\projectlombok\lombok\1.18.30\lombok-1.18.30.jar;D:\maven-repo\repository\io\netty\netty-all\4.1.65.Final\netty-all-4.1.65.Final.jar;D:\maven-repo\repository\org\apache\curator\curator-recipes\5.1.0\curator-recipes-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-framework\5.1.0\curator-framework-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-client\5.1.0\curator-client-5.1.0.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper\3.6.0\zookeeper-3.6.0.jar;D:\maven-repo\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper-jute\3.6.0\zookeeper-jute-3.6.0.jar;D:\maven-repo\repository\org\apache\yetus\audience-annotations\0.5.0\audience-annotations-0.5.0.jar;D:\maven-repo\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-epoll\4.1.45.Final\netty-transport-native-epoll-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-unix-common\4.1.45.Final\netty-transport-native-unix-common-4.1.45.Final.jar;D:\maven-repo\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\maven-repo\repository\org\slf4j\slf4j-api\2.0.9\slf4j-api-2.0.9.jar;D:\maven-repo\repository\ch\qos\logback\logback-classic\1.4.11\logback-classic-1.4.11.jar;D:\maven-repo\repository\ch\qos\logback\logback-core\1.4.11\logback-core-1.4.11.jar;D:\maven-repo\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;D:\maven-repo\repository\com\google\protobuf\protobuf-java\4.30.2\protobuf-java-4.30.2.jar;D:\maven-repo\repository\com\github\rholder\guava-retrying\2.0.0\guava-retrying-2.0.0.jar;D:\maven-repo\repository\com\google\guava\guava\33.4.8-jre\guava-33.4.8-jre.jar;D:\maven-repo\repository\com\google\guava\failureaccess\1.0.3\failureaccess-1.0.3.jar;D:\maven-repo\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\maven-repo\repository\org\jspecify\jspecify\1.0.0\jspecify-1.0.0.jar;D:\maven-repo\repository\com\google\errorprone\error_prone_annotations\2.36.0\error_prone_annotations-2.36.0.jar;D:\maven-repo\repository\com\google\j2objc\j2objc-annotations\3.0.0\j2objc-annotations-3.0.0.jar;D:\maven-repo\repository\com\google\code\findbugs\jsr305\2.0.2\jsr305-2.0.2.jar client.TestClient
ping -n 3 127.0.0.1 > nul

REM 第三阶段：关闭第一个服务节点
echo.
echo 第三阶段：关闭第一个服务节点...
taskkill /FI "WINDOWTITLE eq Server1" /F
ping -n 5 127.0.0.1 > nul

REM 再次测试客户端
echo.
echo 再次测试客户端...
java -cp target/classes;D:\maven-repo\repository\org\projectlombok\lombok\1.18.30\lombok-1.18.30.jar;D:\maven-repo\repository\io\netty\netty-all\4.1.65.Final\netty-all-4.1.65.Final.jar;D:\maven-repo\repository\org\apache\curator\curator-recipes\5.1.0\curator-recipes-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-framework\5.1.0\curator-framework-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-client\5.1.0\curator-client-5.1.0.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper\3.6.0\zookeeper-3.6.0.jar;D:\maven-repo\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper-jute\3.6.0\zookeeper-jute-3.6.0.jar;D:\maven-repo\repository\org\apache\yetus\audience-annotations\0.5.0\audience-annotations-0.5.0.jar;D:\maven-repo\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-epoll\4.1.45.Final\netty-transport-native-epoll-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-unix-common\4.1.45.Final\netty-transport-native-unix-common-4.1.45.Final.jar;D:\maven-repo\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\maven-repo\repository\org\slf4j\slf4j-api\2.0.9\slf4j-api-2.0.9.jar;D:\maven-repo\repository\ch\qos\logback\logback-classic\1.4.11\logback-classic-1.4.11.jar;D:\maven-repo\repository\ch\qos\logback\logback-core\1.4.11\logback-core-1.4.11.jar;D:\maven-repo\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;D:\maven-repo\repository\com\google\protobuf\protobuf-java\4.30.2\protobuf-java-4.30.2.jar;D:\maven-repo\repository\com\github\rholder\guava-retrying\2.0.0\guava-retrying-2.0.0.jar;D:\maven-repo\repository\com\google\guava\guava\33.4.8-jre\guava-33.4.8-jre.jar;D:\maven-repo\repository\com\google\guava\failureaccess\1.0.3\failureaccess-1.0.3.jar;D:\maven-repo\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\maven-repo\repository\org\jspecify\jspecify\1.0.0\jspecify-1.0.0.jar;D:\maven-repo\repository\com\google\errorprone\error_prone_annotations\2.36.0\error_prone_annotations-2.36.0.jar;D:\maven-repo\repository\com\google\j2objc\j2objc-annotations\3.0.0\j2objc-annotations-3.0.0.jar;D:\maven-repo\repository\com\google\code\findbugs\jsr305\2.0.2\jsr305-2.0.2.jar client.TestClient
ping -n 3 127.0.0.1 > nul

REM 第四阶段：关闭第二个服务节点
echo.
echo 第四阶段：关闭第二个服务节点...
taskkill /FI "WINDOWTITLE eq Server2" /F
ping -n 5 127.0.0.1 > nul

REM 最后测试客户端
echo.
echo 最后测试客户端...
java -cp target/classes;D:\maven-repo\repository\org\projectlombok\lombok\1.18.30\lombok-1.18.30.jar;D:\maven-repo\repository\io\netty\netty-all\4.1.65.Final\netty-all-4.1.65.Final.jar;D:\maven-repo\repository\org\apache\curator\curator-recipes\5.1.0\curator-recipes-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-framework\5.1.0\curator-framework-5.1.0.jar;D:\maven-repo\repository\org\apache\curator\curator-client\5.1.0\curator-client-5.1.0.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper\3.6.0\zookeeper-3.6.0.jar;D:\maven-repo\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\maven-repo\repository\org\apache\zookeeper\zookeeper-jute\3.6.0\zookeeper-jute-3.6.0.jar;D:\maven-repo\repository\org\apache\yetus\audience-annotations\0.5.0\audience-annotations-0.5.0.jar;D:\maven-repo\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-epoll\4.1.45.Final\netty-transport-native-epoll-4.1.45.Final.jar;D:\maven-repo\repository\io\netty\netty-transport-native-unix-common\4.1.45.Final\netty-transport-native-unix-common-4.1.45.Final.jar;D:\maven-repo\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\maven-repo\repository\org\slf4j\slf4j-api\2.0.9\slf4j-api-2.0.9.jar;D:\maven-repo\repository\ch\qos\logback\logback-classic\1.4.11\logback-classic-1.4.11.jar;D:\maven-repo\repository\ch\qos\logback\logback-core\1.4.11\logback-core-1.4.11.jar;D:\maven-repo\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;D:\maven-repo\repository\com\google\protobuf\protobuf-java\4.30.2\protobuf-java-4.30.2.jar;D:\maven-repo\repository\com\github\rholder\guava-retrying\2.0.0\guava-retrying-2.0.0.jar;D:\maven-repo\repository\com\google\guava\guava\33.4.8-jre\guava-33.4.8-jre.jar;D:\maven-repo\repository\com\google\guava\failureaccess\1.0.3\failureaccess-1.0.3.jar;D:\maven-repo\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\maven-repo\repository\org\jspecify\jspecify\1.0.0\jspecify-1.0.0.jar;D:\maven-repo\repository\com\google\errorprone\error_prone_annotations\2.36.0\error_prone_annotations-2.36.0.jar;D:\maven-repo\repository\com\google\j2objc\j2objc-annotations\3.0.0\j2objc-annotations-3.0.0.jar;D:\maven-repo\repository\com\google\code\findbugs\jsr305\2.0.2\jsr305-2.0.2.jar client.TestClient

echo.
echo 测试完成！ 