// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/rpc.proto
// Protobuf Java Version: 4.30.2

package common.message;

public final class Rpc {
  private Rpc() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Rpc.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.message.RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 添加interfaceName字段
     * </pre>
     *
     * <code>string interfaceName = 1;</code>
     * @return The interfaceName.
     */
    java.lang.String getInterfaceName();
    /**
     * <pre>
     * 添加interfaceName字段
     * </pre>
     *
     * <code>string interfaceName = 1;</code>
     * @return The bytes for interfaceName.
     */
    com.google.protobuf.ByteString
        getInterfaceNameBytes();

    /**
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated string params = 3;</code>
     * @return A list containing the params.
     */
    java.util.List<java.lang.String>
        getParamsList();
    /**
     * <code>repeated string params = 3;</code>
     * @return The count of params.
     */
    int getParamsCount();
    /**
     * <code>repeated string params = 3;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    java.lang.String getParams(int index);
    /**
     * <code>repeated string params = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the params at the given index.
     */
    com.google.protobuf.ByteString
        getParamsBytes(int index);

    /**
     * <code>repeated string paramsType = 4;</code>
     * @return A list containing the paramsType.
     */
    java.util.List<java.lang.String>
        getParamsTypeList();
    /**
     * <code>repeated string paramsType = 4;</code>
     * @return The count of paramsType.
     */
    int getParamsTypeCount();
    /**
     * <code>repeated string paramsType = 4;</code>
     * @param index The index of the element to return.
     * @return The paramsType at the given index.
     */
    java.lang.String getParamsType(int index);
    /**
     * <code>repeated string paramsType = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramsType at the given index.
     */
    com.google.protobuf.ByteString
        getParamsTypeBytes(int index);

    /**
     * <pre>
     * 添加时间戳字段，用于负载均衡
     * </pre>
     *
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code common.message.RpcRequest}
   */
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.message.RpcRequest)
      RpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        RpcRequest.class.getName());
    }
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RpcRequest() {
      interfaceName_ = "";
      methodName_ = "";
      params_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      paramsType_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.message.Rpc.internal_static_common_message_RpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.message.Rpc.internal_static_common_message_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common.message.Rpc.RpcRequest.class, common.message.Rpc.RpcRequest.Builder.class);
    }

    public static final int INTERFACENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object interfaceName_ = "";
    /**
     * <pre>
     * 添加interfaceName字段
     * </pre>
     *
     * <code>string interfaceName = 1;</code>
     * @return The interfaceName.
     */
    @java.lang.Override
    public java.lang.String getInterfaceName() {
      java.lang.Object ref = interfaceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interfaceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 添加interfaceName字段
     * </pre>
     *
     * <code>string interfaceName = 1;</code>
     * @return The bytes for interfaceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
      java.lang.Object ref = interfaceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object methodName_ = "";
    /**
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList params_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string params = 3;</code>
     * @return A list containing the params.
     */
    public com.google.protobuf.ProtocolStringList
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated string params = 3;</code>
     * @return The count of params.
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated string params = 3;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    public java.lang.String getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated string params = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the params at the given index.
     */
    public com.google.protobuf.ByteString
        getParamsBytes(int index) {
      return params_.getByteString(index);
    }

    public static final int PARAMSTYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList paramsType_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string paramsType = 4;</code>
     * @return A list containing the paramsType.
     */
    public com.google.protobuf.ProtocolStringList
        getParamsTypeList() {
      return paramsType_;
    }
    /**
     * <code>repeated string paramsType = 4;</code>
     * @return The count of paramsType.
     */
    public int getParamsTypeCount() {
      return paramsType_.size();
    }
    /**
     * <code>repeated string paramsType = 4;</code>
     * @param index The index of the element to return.
     * @return The paramsType at the given index.
     */
    public java.lang.String getParamsType(int index) {
      return paramsType_.get(index);
    }
    /**
     * <code>repeated string paramsType = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramsType at the given index.
     */
    public com.google.protobuf.ByteString
        getParamsTypeBytes(int index) {
      return paramsType_.getByteString(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_ = 0L;
    /**
     * <pre>
     * 添加时间戳字段，用于负载均衡
     * </pre>
     *
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(interfaceName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, interfaceName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, methodName_);
      }
      for (int i = 0; i < params_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, params_.getRaw(i));
      }
      for (int i = 0; i < paramsType_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, paramsType_.getRaw(i));
      }
      if (timestamp_ != 0L) {
        output.writeInt64(5, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(interfaceName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, interfaceName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, methodName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += computeStringSizeNoTag(params_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramsType_.size(); i++) {
          dataSize += computeStringSizeNoTag(paramsType_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamsTypeList().size();
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof common.message.Rpc.RpcRequest)) {
        return super.equals(obj);
      }
      common.message.Rpc.RpcRequest other = (common.message.Rpc.RpcRequest) obj;

      if (!getInterfaceName()
          .equals(other.getInterfaceName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!getParamsTypeList()
          .equals(other.getParamsTypeList())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTERFACENAME_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      if (getParamsTypeCount() > 0) {
        hash = (37 * hash) + PARAMSTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getParamsTypeList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static common.message.Rpc.RpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common.message.Rpc.RpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common.message.Rpc.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common.message.Rpc.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common.message.Rpc.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common.message.Rpc.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common.message.Rpc.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static common.message.Rpc.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static common.message.Rpc.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static common.message.Rpc.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static common.message.Rpc.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static common.message.Rpc.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(common.message.Rpc.RpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.message.RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.message.RpcRequest)
        common.message.Rpc.RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return common.message.Rpc.internal_static_common_message_RpcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return common.message.Rpc.internal_static_common_message_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                common.message.Rpc.RpcRequest.class, common.message.Rpc.RpcRequest.Builder.class);
      }

      // Construct using common.message.Rpc.RpcRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        interfaceName_ = "";
        methodName_ = "";
        params_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        paramsType_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common.message.Rpc.internal_static_common_message_RpcRequest_descriptor;
      }

      @java.lang.Override
      public common.message.Rpc.RpcRequest getDefaultInstanceForType() {
        return common.message.Rpc.RpcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public common.message.Rpc.RpcRequest build() {
        common.message.Rpc.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public common.message.Rpc.RpcRequest buildPartial() {
        common.message.Rpc.RpcRequest result = new common.message.Rpc.RpcRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(common.message.Rpc.RpcRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.interfaceName_ = interfaceName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.methodName_ = methodName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          params_.makeImmutable();
          result.params_ = params_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          paramsType_.makeImmutable();
          result.paramsType_ = paramsType_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common.message.Rpc.RpcRequest) {
          return mergeFrom((common.message.Rpc.RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(common.message.Rpc.RpcRequest other) {
        if (other == common.message.Rpc.RpcRequest.getDefaultInstance()) return this;
        if (!other.getInterfaceName().isEmpty()) {
          interfaceName_ = other.interfaceName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ |= 0x00000004;
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        if (!other.paramsType_.isEmpty()) {
          if (paramsType_.isEmpty()) {
            paramsType_ = other.paramsType_;
            bitField0_ |= 0x00000008;
          } else {
            ensureParamsTypeIsMutable();
            paramsType_.addAll(other.paramsType_);
          }
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                interfaceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                methodName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureParamsIsMutable();
                params_.add(s);
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureParamsTypeIsMutable();
                paramsType_.add(s);
                break;
              } // case 34
              case 40: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object interfaceName_ = "";
      /**
       * <pre>
       * 添加interfaceName字段
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @return The interfaceName.
       */
      public java.lang.String getInterfaceName() {
        java.lang.Object ref = interfaceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interfaceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 添加interfaceName字段
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @return The bytes for interfaceName.
       */
      public com.google.protobuf.ByteString
          getInterfaceNameBytes() {
        java.lang.Object ref = interfaceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 添加interfaceName字段
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @param value The interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        interfaceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 添加interfaceName字段
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterfaceName() {
        interfaceName_ = getDefaultInstance().getInterfaceName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 添加interfaceName字段
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @param value The bytes for interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        interfaceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string methodName = 2;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string methodName = 2;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string methodName = 2;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        methodName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        methodName_ = getDefaultInstance().getMethodName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 2;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        methodName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList params_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureParamsIsMutable() {
        if (!params_.isModifiable()) {
          params_ = new com.google.protobuf.LazyStringArrayList(params_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated string params = 3;</code>
       * @return A list containing the params.
       */
      public com.google.protobuf.ProtocolStringList
          getParamsList() {
        params_.makeImmutable();
        return params_;
      }
      /**
       * <code>repeated string params = 3;</code>
       * @return The count of params.
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated string params = 3;</code>
       * @param index The index of the element to return.
       * @return The params at the given index.
       */
      public java.lang.String getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated string params = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the params at the given index.
       */
      public com.google.protobuf.ByteString
          getParamsBytes(int index) {
        return params_.getByteString(index);
      }
      /**
       * <code>repeated string params = 3;</code>
       * @param index The index to set the value at.
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamsIsMutable();
        params_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 3;</code>
       * @param value The params to add.
       * @return This builder for chaining.
       */
      public Builder addParams(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamsIsMutable();
        params_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 3;</code>
       * @param values The params to add.
       * @return This builder for chaining.
       */
      public Builder addAllParams(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, params_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        params_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 3;</code>
       * @param value The bytes of the params to add.
       * @return This builder for chaining.
       */
      public Builder addParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParamsIsMutable();
        params_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList paramsType_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureParamsTypeIsMutable() {
        if (!paramsType_.isModifiable()) {
          paramsType_ = new com.google.protobuf.LazyStringArrayList(paramsType_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @return A list containing the paramsType.
       */
      public com.google.protobuf.ProtocolStringList
          getParamsTypeList() {
        paramsType_.makeImmutable();
        return paramsType_;
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @return The count of paramsType.
       */
      public int getParamsTypeCount() {
        return paramsType_.size();
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @param index The index of the element to return.
       * @return The paramsType at the given index.
       */
      public java.lang.String getParamsType(int index) {
        return paramsType_.get(index);
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the paramsType at the given index.
       */
      public com.google.protobuf.ByteString
          getParamsTypeBytes(int index) {
        return paramsType_.getByteString(index);
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @param index The index to set the value at.
       * @param value The paramsType to set.
       * @return This builder for chaining.
       */
      public Builder setParamsType(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamsTypeIsMutable();
        paramsType_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @param value The paramsType to add.
       * @return This builder for chaining.
       */
      public Builder addParamsType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamsTypeIsMutable();
        paramsType_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @param values The paramsType to add.
       * @return This builder for chaining.
       */
      public Builder addAllParamsType(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamsTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramsType_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParamsType() {
        paramsType_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramsType = 4;</code>
       * @param value The bytes of the paramsType to add.
       * @return This builder for chaining.
       */
      public Builder addParamsTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParamsTypeIsMutable();
        paramsType_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 添加时间戳字段，用于负载均衡
       * </pre>
       *
       * <code>int64 timestamp = 5;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 添加时间戳字段，用于负载均衡
       * </pre>
       *
       * <code>int64 timestamp = 5;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 添加时间戳字段，用于负载均衡
       * </pre>
       *
       * <code>int64 timestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.message.RpcRequest)
    }

    // @@protoc_insertion_point(class_scope:common.message.RpcRequest)
    private static final common.message.Rpc.RpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new common.message.Rpc.RpcRequest();
    }

    public static common.message.Rpc.RpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
      @java.lang.Override
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public common.message.Rpc.RpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.message.RpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string data = 1;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 1;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>string dataType = 2;</code>
     * @return The dataType.
     */
    java.lang.String getDataType();
    /**
     * <code>string dataType = 2;</code>
     * @return The bytes for dataType.
     */
    com.google.protobuf.ByteString
        getDataTypeBytes();

    /**
     * <pre>
     * 添加code字段
     * </pre>
     *
     * <code>int32 code = 3;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * 添加message字段
     * </pre>
     *
     * <code>string message = 4;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 添加message字段
     * </pre>
     *
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 添加服务器地址字段
     * </pre>
     *
     * <code>string serverAddress = 5;</code>
     * @return The serverAddress.
     */
    java.lang.String getServerAddress();
    /**
     * <pre>
     * 添加服务器地址字段
     * </pre>
     *
     * <code>string serverAddress = 5;</code>
     * @return The bytes for serverAddress.
     */
    com.google.protobuf.ByteString
        getServerAddressBytes();
  }
  /**
   * Protobuf type {@code common.message.RpcResponse}
   */
  public static final class RpcResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.message.RpcResponse)
      RpcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        RpcResponse.class.getName());
    }
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RpcResponse() {
      data_ = "";
      dataType_ = "";
      message_ = "";
      serverAddress_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.message.Rpc.internal_static_common_message_RpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.message.Rpc.internal_static_common_message_RpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common.message.Rpc.RpcResponse.class, common.message.Rpc.RpcResponse.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object data_ = "";
    /**
     * <code>string data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 1;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATATYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dataType_ = "";
    /**
     * <code>string dataType = 2;</code>
     * @return The dataType.
     */
    @java.lang.Override
    public java.lang.String getDataType() {
      java.lang.Object ref = dataType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataType_ = s;
        return s;
      }
    }
    /**
     * <code>string dataType = 2;</code>
     * @return The bytes for dataType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      java.lang.Object ref = dataType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_ = 0;
    /**
     * <pre>
     * 添加code字段
     * </pre>
     *
     * <code>int32 code = 3;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 添加message字段
     * </pre>
     *
     * <code>string message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 添加message字段
     * </pre>
     *
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERADDRESS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serverAddress_ = "";
    /**
     * <pre>
     * 添加服务器地址字段
     * </pre>
     *
     * <code>string serverAddress = 5;</code>
     * @return The serverAddress.
     */
    @java.lang.Override
    public java.lang.String getServerAddress() {
      java.lang.Object ref = serverAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 添加服务器地址字段
     * </pre>
     *
     * <code>string serverAddress = 5;</code>
     * @return The bytes for serverAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerAddressBytes() {
      java.lang.Object ref = serverAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, data_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, dataType_);
      }
      if (code_ != 0) {
        output.writeInt32(3, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, message_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverAddress_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, serverAddress_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, data_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, dataType_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, message_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverAddress_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, serverAddress_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof common.message.Rpc.RpcResponse)) {
        return super.equals(obj);
      }
      common.message.Rpc.RpcResponse other = (common.message.Rpc.RpcResponse) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!getDataType()
          .equals(other.getDataType())) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getServerAddress()
          .equals(other.getServerAddress())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataType().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + SERVERADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getServerAddress().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static common.message.Rpc.RpcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common.message.Rpc.RpcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common.message.Rpc.RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common.message.Rpc.RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common.message.Rpc.RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common.message.Rpc.RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common.message.Rpc.RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static common.message.Rpc.RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static common.message.Rpc.RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static common.message.Rpc.RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static common.message.Rpc.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static common.message.Rpc.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(common.message.Rpc.RpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.message.RpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.message.RpcResponse)
        common.message.Rpc.RpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return common.message.Rpc.internal_static_common_message_RpcResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return common.message.Rpc.internal_static_common_message_RpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                common.message.Rpc.RpcResponse.class, common.message.Rpc.RpcResponse.Builder.class);
      }

      // Construct using common.message.Rpc.RpcResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        data_ = "";
        dataType_ = "";
        code_ = 0;
        message_ = "";
        serverAddress_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common.message.Rpc.internal_static_common_message_RpcResponse_descriptor;
      }

      @java.lang.Override
      public common.message.Rpc.RpcResponse getDefaultInstanceForType() {
        return common.message.Rpc.RpcResponse.getDefaultInstance();
      }

      @java.lang.Override
      public common.message.Rpc.RpcResponse build() {
        common.message.Rpc.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public common.message.Rpc.RpcResponse buildPartial() {
        common.message.Rpc.RpcResponse result = new common.message.Rpc.RpcResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(common.message.Rpc.RpcResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dataType_ = dataType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.serverAddress_ = serverAddress_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common.message.Rpc.RpcResponse) {
          return mergeFrom((common.message.Rpc.RpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(common.message.Rpc.RpcResponse other) {
        if (other == common.message.Rpc.RpcResponse.getDefaultInstance()) return this;
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDataType().isEmpty()) {
          dataType_ = other.dataType_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getServerAddress().isEmpty()) {
          serverAddress_ = other.serverAddress_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                data_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                dataType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                serverAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 1;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 1;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = getDefaultInstance().getData();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string data = 1;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        data_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object dataType_ = "";
      /**
       * <code>string dataType = 2;</code>
       * @return The dataType.
       */
      public java.lang.String getDataType() {
        java.lang.Object ref = dataType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dataType = 2;</code>
       * @return The bytes for dataType.
       */
      public com.google.protobuf.ByteString
          getDataTypeBytes() {
        java.lang.Object ref = dataType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataType = 2;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dataType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string dataType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        dataType_ = getDefaultInstance().getDataType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string dataType = 2;</code>
       * @param value The bytes for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dataType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * 添加code字段
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 添加code字段
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 添加code字段
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 添加message字段
       * </pre>
       *
       * <code>string message = 4;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 添加message字段
       * </pre>
       *
       * <code>string message = 4;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 添加message字段
       * </pre>
       *
       * <code>string message = 4;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 添加message字段
       * </pre>
       *
       * <code>string message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 添加message字段
       * </pre>
       *
       * <code>string message = 4;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object serverAddress_ = "";
      /**
       * <pre>
       * 添加服务器地址字段
       * </pre>
       *
       * <code>string serverAddress = 5;</code>
       * @return The serverAddress.
       */
      public java.lang.String getServerAddress() {
        java.lang.Object ref = serverAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 添加服务器地址字段
       * </pre>
       *
       * <code>string serverAddress = 5;</code>
       * @return The bytes for serverAddress.
       */
      public com.google.protobuf.ByteString
          getServerAddressBytes() {
        java.lang.Object ref = serverAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 添加服务器地址字段
       * </pre>
       *
       * <code>string serverAddress = 5;</code>
       * @param value The serverAddress to set.
       * @return This builder for chaining.
       */
      public Builder setServerAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serverAddress_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 添加服务器地址字段
       * </pre>
       *
       * <code>string serverAddress = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerAddress() {
        serverAddress_ = getDefaultInstance().getServerAddress();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 添加服务器地址字段
       * </pre>
       *
       * <code>string serverAddress = 5;</code>
       * @param value The bytes for serverAddress to set.
       * @return This builder for chaining.
       */
      public Builder setServerAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serverAddress_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.message.RpcResponse)
    }

    // @@protoc_insertion_point(class_scope:common.message.RpcResponse)
    private static final common.message.Rpc.RpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new common.message.Rpc.RpcResponse();
    }

    public static common.message.Rpc.RpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<RpcResponse>() {
      @java.lang.Override
      public RpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RpcResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public common.message.Rpc.RpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_message_RpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_message_RpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_message_RpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_message_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030src/main/proto/rpc.proto\022\016common.messa" +
      "ge\"n\n\nRpcRequest\022\025\n\rinterfaceName\030\001 \001(\t\022" +
      "\022\n\nmethodName\030\002 \001(\t\022\016\n\006params\030\003 \003(\t\022\022\n\np" +
      "aramsType\030\004 \003(\t\022\021\n\ttimestamp\030\005 \001(\003\"c\n\013Rp" +
      "cResponse\022\014\n\004data\030\001 \001(\t\022\020\n\010dataType\030\002 \001(" +
      "\t\022\014\n\004code\030\003 \001(\005\022\017\n\007message\030\004 \001(\t\022\025\n\rserv" +
      "erAddress\030\005 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_message_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_message_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_message_RpcRequest_descriptor,
        new java.lang.String[] { "InterfaceName", "MethodName", "Params", "ParamsType", "Timestamp", });
    internal_static_common_message_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_message_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_message_RpcResponse_descriptor,
        new java.lang.String[] { "Data", "DataType", "Code", "Message", "ServerAddress", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
